Credo fixes
infinity-aps/pummpcomm pull request #6
Opened 2017-09-14 05:19 UTC by KronicDeth

# Changelog
## Bug Fixes
* Fix credo warnings that cause a non-zero exit status.  You can now turn on `credo --strict` to stop the build when it exits non-zero if you want.
  * While fixing `@moduledocs` in those modules, also document their types and functions, so that most undocumented functions are now documented too with `@doc` and `@spec`.
  * Fix lines > 120 characters
  * Remove `()` from function definitons

2017-09-14 13:12 UTC, tmecklem requested changes
This is amazing work. You've educated me about some of the pump history details that I've wondered about.

2017-09-14 13:12 UTC, tmecklem commented on lib/pummpcomm/cgm/timestamper.ex
> +  If the event can serve as a reference timestamp for relative events that follow it
Reference timestamps are weird on cgm pages, and actually serve as a reference for preceding events rather than for events that follow. 

There's a command for the pump to write a cgm page timestamp when one is required (https://github.com/infinity-aps/pummpcomm/blob/master/lib/pummpcomm/session/exchange/write_cgm_timestamp.ex). It took quite a while to piece together why that command exists, but every time the pump did a carelink dump a new timestamp showed up, and I realized it was so that the events in cgm history would have a reference.

Once decoding is finished and timestamping has been applied, the https://github.com/infinity-aps/pummpcomm/blob/144b589b43d6b0d0bf929428f11cb25dd5b18a4d/lib/pummpcomm/cgm.ex#L164 `needs_timestamp?` function will check to see if any entries in the page can't be timestamped.

The `try_find_timestamp` function does a little bit of work to keep from having to write a timestamp every time an entry is written in order to keep the cgm pages uncluttered. https://github.com/infinity-aps/pummpcomm/blob/144b589b43d6b0d0bf929428f11cb25dd5b18a4d/lib/pummpcomm/cgm/timestamper.ex#L37. This relative offset timestamping may be the most confusing part of the code and I want it to be clearer in communicating the intent.

2017-09-14 13:12 UTC, tmecklem commented on lib/pummpcomm/history/alarm_sensor.ex
> +  * `"Lost Sensor"` - Signal from CGM went noiser than `"Weak Signal"` and communication was completely lost.  Move CGM
These are great descriptions. Some of this is information I didn't know. 

Either there's a typo here and you meant "noisier" or I need to increase my vocabulary.

2017-09-14 13:12 UTC, tmecklem commented on lib/pummpcomm/cgm/timestamper.ex
> +  If the event's timestamp is relative to the preceeding reference event's timestamp
See above comment re reference timestamps. I think if you just remove "preceeding" from here it still communicates the information and is slightly more accurate.

2017-09-14 13:12 UTC, tmecklem commented on lib/pummpcomm/cgm/timestamper.ex
> +  Adds timestamps to all relative events in `events` using the preceeding reference event's timestamp
See above comment re reference timestamps. I think if you just remove "preceeding" from here it still communicates the information and is slightly more accurate.

2017-09-14 13:12 UTC, tmecklem commented on lib/pummpcomm/history/alarm_pump.ex
> +  An alaram raised by the pump about its internal operations.
Small typo here on alarm

2017-09-14 13:12 UTC, tmecklem commented on lib/pummpcomm/history/change_carb_units.ex
> +  When carbohydrates units is switched between grames and exchanges
Typo on "grams"

2017-09-14 13:12 UTC, tmecklem commented on lib/pummpcomm/history/change_carb_units.ex
> +  `timestamp` when carbohydrates units is switched between grames and exchanges
Typo on "grams"

2017-09-14 13:12 UTC, tmecklem commented on lib/pummpcomm/history/low_reservoir.ex
> +  `timestamp` when Low Reservior alarm was raised with `amount` units left.
Typo on reservoir.

2017-09-14 13:12 UTC, tmecklem commented on lib/pummpcomm/history/prime.ex
> +  When a new canula was primed
Typo on cannula

2017-09-14 13:12 UTC, tmecklem commented on lib/pummpcomm/history/prime.ex
> +  * `:fixed` - user used the fixed prime value of `0.5` or `0.9` for the canula type
Typo on cannula

2017-09-14 13:12 UTC, tmecklem commented on lib/pummpcomm/history/prime.ex
> +  `timestamp` when canula was primed with `prime_type`.
Typo on cannula

2017-09-14 13:12 UTC, tmecklem commented on lib/pummpcomm/session/exchange/get_current_cgm_page.ex
> +  Get current CGM page from pump.  To read a past page from the CGM, use `Pummpcomm.Session.Exchange.ReadCgmPage`.
GetCurrentCgmPage returns an integer for the current cgm `page_number` (as well as the number of cgm `glucose` pages and `isig` pages actually stored on the pump, 32 in all the experiences I've had). So to read the current actual binary page, you still have to take the response from this command and call ReadCgmPage. I think that isn't quite made clear by this doc yet, but you're moving in the right direction.

To expand on the `glucose` and `isig` part, If your current cgm page is 58, you can only read 32 pages back of history before the pump wraps around and starts overwriting older pages. So you can't actually fetch all the way to 0. History pages work the same way.

2017-09-14 13:12 UTC, tmecklem commented on lib/pummpcomm/session/exchange/read_cgm_page.ex
> +  Reads a (past) CGM page.  To cread the current CGM page, use `Pummpcomm.Session.Exchange.GetCurrentCgmPage`.
See other comment on GetCurrentCgmPage. This is pretty close documentation, but not quite 100% accurate.

A little more trivia, cgm pages count up, so page 1 comes before page 2 and the number climbs as new pages are written. That why GetCurrentCgmPage has to exist, so we can fetch the current page's index. History pages are the opposite. Getting history page 0 is always the most recent, and to fetch older pages you fetch 1 then 2, etc. So for history, there's no corresponding GetCurrentHistoryPage call.

2017-09-14 13:12 UTC, tmecklem commented on lib/pummpcomm/session/exchange/read_pump_status.ex
> +  Reads status of pump: wether it's bolusing or suspeneded.
Typos on "whether" and "suspended"

2017-09-14 13:12 UTC, tmecklem commented on lib/pummpcomm/session/exchange/read_remaining_insulin.ex
> +  Makes `Pummpcomm.Session.Command.t` to read remaining `Pummpcomm.Insulin.units` in reservour from pump with
Typo on "reservoir"

2017-09-14 13:12 UTC, tmecklem commented on lib/pummpcomm/session/exchange/read_settings.ex
> +  Reads settings about max basal, max bolus, selected basal profile (for basal profile patterns) and the insultin action
Typo on "insulin"

2017-09-14 13:12 UTC, tmecklem commented on lib/pummpcomm/session/exchange/read_settings.ex
> +  (for basal profile patterns) and the insultin action curve in hours from pump with `pump_serial`
Typo on "insulin"

2017-09-14 13:12 UTC, tmecklem commented on lib/pummpcomm/session/exchange/read_settings.ex
> +  (for basal profile patterns) and the insultin action curve in hours from pump with `pump_serial`
Typo on "insulin"

2017-09-14 13:12 UTC, tmecklem commented on lib/pummpcomm/session/exchange/read_temp_basal.ex
> +  Reads temporaray basal from pump
Typo on "temporary"

2017-09-14 13:12 UTC, tmecklem commented on lib/pummpcomm/session/response.ex
> +  * `frames` - accumulated frames, for a multi-frame response.  Frames are in reverse-order.
Mentioning the order of the data and frames here is great!

2017-09-15 02:09 UTC, KronicDeth commented
All change requests have been addressed with `fixup`s and rebased in.

2017-09-15 04:26 UTC, tmecklem approved these changes

2017-09-15 04:27 UTC, merged